/**
 * Build theme CSS from parsed MDX tokens for landing page previews.
 */

function radiusVars(style) {
	switch (style) {
		case "sharp":
			return { sm: "0px", md: "0px", lg: "0px", full: "0px" };
		case "pill":
			return { sm: "8px", md: "12px", lg: "16px", full: "9999px" };
		case "soft":
			return { sm: "8px", md: "16px", lg: "24px", full: "9999px" };
		default:
			return { sm: "6px", md: "12px", lg: "16px", full: "9999px" };
	}
}

function effectCss(effect, tokens) {
	const { accent, accent2, foreground, border } = tokens;
	switch (effect) {
		case "brutal":
			return `
        .lp-btn-primary { border: 4px solid ${foreground}; box-shadow: 4px 4px 0 ${foreground}; font-weight: 700; text-transform: uppercase; }
        .lp-btn-primary:hover { transform: translate(2px, 2px); box-shadow: 2px 2px 0 ${foreground}; }
        .lp-card, .lp-nav, .lp-input { border-width: 3px; border-color: ${foreground}; box-shadow: 4px 4px 0 ${foreground}; }
        .lp-heading { font-weight: 900; letter-spacing: -0.04em; }
      `;
		case "neon":
			return `
        .lp-btn-primary { box-shadow: 0 0 20px ${accent}; }
        .lp-card { border-color: ${accent2}; box-shadow: 0 0 20px rgba(255,0,255,0.15); }
        .lp-heading-gradient { background: linear-gradient(90deg, #FF9900, ${accent}, ${accent2}); -webkit-background-clip: text; background-clip: text; color: transparent; }
        .lp-hero-glow { background: radial-gradient(circle, ${accent}33 0%, transparent 60%); }
      `;
		case "glow":
			return `
        .lp-btn-primary { box-shadow: 0 0 24px ${accent}55; }
        .lp-card:hover { box-shadow: 0 8px 32px ${accent}22; }
        .lp-hero-glow { background: radial-gradient(circle, ${accent}18 0%, transparent 65%); }
      `;
		case "neumorph":
			return `
        .lp-card, .lp-input { box-shadow: 8px 8px 16px #a3b1c6, -8px -8px 16px #ffffff; border: none; }
        .lp-surface { background: var(--lp-bg); }
      `;
		case "clay":
			return `
        .lp-card { box-shadow: inset -2px -2px 8px rgba(0,0,0,0.08), 8px 8px 20px rgba(0,0,0,0.06); }
      `;
		case "terminal":
			return `
        body { font-family: var(--lp-font), monospace; }
        .lp-btn-primary { border: 1px solid ${accent}; color: ${accent}; background: transparent; }
        .lp-card { border: 1px solid ${border}; }
        .lp-text-muted { color: ${accent}99; }
      `;
		case "sketch":
			return `
        .lp-card { border: 2px dashed ${border}; transform: rotate(-0.3deg); }
        .lp-btn-primary { border: 2px solid ${foreground}; border-radius: 255px 15px 225px 15px/15px 225px 15px 255px; }
      `;
		default:
			return `
        .lp-hero-glow { background: radial-gradient(circle, ${accent}14 0%, transparent 65%); }
      `;
	}
}

export function buildThemeLandingCss(tokens, themeName) {
	const r = radiusVars(tokens.radiusStyle);
	const fontParam = encodeURIComponent(tokens.fontFamily.replace(/ /g, "+"));

	return `
/* Theme: ${themeName} — generated by scripts/generate-theme-landing-pages.js */
@import url('https://fonts.googleapis.com/css2?family=${fontParam}:wght@400;500;600;700;900&display=swap');

:root {
  --lp-bg: ${tokens.background};
  --lp-surface: ${tokens.surface};
  --lp-fg: ${tokens.foreground};
  --lp-muted: ${tokens.muted};
  --lp-accent: ${tokens.accent};
  --lp-accent-2: ${tokens.accent2};
  --lp-border: ${tokens.border};
  --lp-radius-sm: ${r.sm};
  --lp-radius-md: ${r.md};
  --lp-radius-lg: ${r.lg};
  --lp-radius-full: ${r.full};
  --lp-font: '${tokens.fontFamily}', system-ui, sans-serif;
}

* { box-sizing: border-box; }
body.lp-body {
  margin: 0;
  font-family: var(--lp-font);
  background: var(--lp-bg);
  color: var(--lp-fg);
  -webkit-font-smoothing: antialiased;
}

.lp-text-muted { color: color-mix(in srgb, var(--lp-fg) 55%, transparent); }
.lp-text-subtle { color: color-mix(in srgb, var(--lp-fg) 40%, transparent); }
.lp-surface { background: var(--lp-surface); }
.lp-border { border-color: var(--lp-border); }
.lp-accent { color: var(--lp-accent); }
.lp-bg-accent { background: var(--lp-accent); }
.lp-bg-muted { background: var(--lp-muted); }

.lp-nav {
  background: color-mix(in srgb, var(--lp-bg) 88%, transparent);
  backdrop-filter: blur(12px);
  border-bottom: 1px solid var(--lp-border);
}

.lp-card {
  background: var(--lp-surface);
  border: 1px solid var(--lp-border);
  border-radius: var(--lp-radius-lg);
  transition: transform 0.2s, box-shadow 0.2s;
}
.lp-card:hover { transform: translateY(-2px); }

.lp-btn-primary {
  background: var(--lp-accent);
  color: ${tokens.mode === "dark" ? tokens.foreground : "#FFFFFF"};
  border: 1px solid var(--lp-border);
  border-radius: var(--lp-radius-full);
  font-weight: 600;
  cursor: pointer;
  transition: opacity 0.2s;
}
.lp-btn-primary:hover { opacity: 0.9; }

.lp-btn-secondary {
  background: var(--lp-surface);
  color: var(--lp-fg);
  border: 1px solid var(--lp-border);
  border-radius: var(--lp-radius-md);
  font-weight: 600;
  cursor: pointer;
}

.lp-input {
  background: var(--lp-surface);
  border: 1px solid var(--lp-border);
  border-radius: var(--lp-radius-md);
  color: var(--lp-fg);
  padding: 0.625rem 1rem;
  width: 100%;
}
.lp-input::placeholder { color: color-mix(in srgb, var(--lp-fg) 40%, transparent); }

.lp-badge {
  display: inline-flex;
  align-items: center;
  gap: 0.5rem;
  padding: 0.25rem 0.75rem;
  border-radius: var(--lp-radius-full);
  border: 1px solid color-mix(in srgb, var(--lp-accent) 40%, var(--lp-border));
  background: color-mix(in srgb, var(--lp-accent) 12%, var(--lp-surface));
  color: var(--lp-accent);
  font-size: 0.75rem;
  font-weight: 600;
}

.lp-heading { color: var(--lp-fg); font-weight: 700; letter-spacing: -0.02em; }
.lp-section { border-top: 1px solid var(--lp-border); }
.lp-footer { background: color-mix(in srgb, var(--lp-muted) 40%, var(--lp-bg)); border-top: 1px solid var(--lp-border); }

.lp-tab-active {
  background: var(--lp-surface);
  border: 1px solid var(--lp-border);
  border-radius: var(--lp-radius-md);
  color: var(--lp-accent);
}

.lp-pricing-featured {
  border: 2px solid var(--lp-accent);
  box-shadow: 0 0 0 4px color-mix(in srgb, var(--lp-accent) 15%, transparent);
}

.lp-faq-item {
  border: 1px solid var(--lp-border);
  border-radius: var(--lp-radius-md);
  background: var(--lp-surface);
}

${effectCss(tokens.effect, tokens)}
`.trim();
}
