/** Target language names for video translate (LLM translation); aligned with common HeyGen-style labels. */
export const VIDEO_TRANSLATE_TARGET_LANGUAGES = [
	"English",
	"Spanish",
	"French",
	"Hindi",
	"Italian",
	"German",
	"Polish",
	"Portuguese",
	"Chinese",
	"Japanese",
	"Dutch",
	"Turkish",
	"Korean",
	"Danish",
	"Arabic",
	"Romanian",
	"Mandarin",
	"Filipino",
	"Swedish",
	"Indonesian",
	"Ukrainian",
	"Greek",
	"Czech",
	"Bulgarian",
	"Malay",
	"Slovak",
	"Croatian",
	"Tamil",
	"Finnish",
	"Russian",
	"Vietnamese",
	"Afrikaans (South Africa)",
	"Albanian (Albania)",
	"Amharic (Ethiopia)",
	"Arabic (Egypt)",
	"Arabic (Saudi Arabia)",
	"Arabic (United Arab Emirates)",
	"Armenian (Armenia)",
	"Bangla (Bangladesh)",
	"Bengali (India)",
	"Catalan",
	"Chinese (Mandarin, Simplified)",
	"Chinese (Cantonese, Traditional)",
	"Chinese (Taiwanese Mandarin, Traditional)",
	"Croatian (Croatia)",
	"Czech (Czechia)",
	"Danish (Denmark)",
	"Dutch (Netherlands)",
	"Dutch (Belgium)",
	"English (United States)",
	"English (UK)",
	"English (India)",
	"Filipino (Philippines)",
	"Finnish (Finland)",
	"French (France)",
	"French (Canada)",
	"German (Germany)",
	"German (Austria)",
	"Greek (Greece)",
	"Gujarati (India)",
	"Hebrew (Israel)",
	"Hindi (India)",
	"Hungarian (Hungary)",
	"Indonesian (Indonesia)",
	"Italian (Italy)",
	"Japanese (Japan)",
	"Kannada (India)",
	"Korean (Korea)",
	"Malay (Malaysia)",
	"Malayalam (India)",
	"Marathi (India)",
	"Norwegian Bokmål (Norway)",
	"Persian (Iran)",
	"Polish (Poland)",
	"Portuguese (Brazil)",
	"Portuguese (Portugal)",
	"Romanian (Romania)",
	"Russian (Russia)",
	"Spanish (Spain)",
	"Spanish (Mexico)",
	"Spanish (United States)",
	"Swedish (Sweden)",
	"Tamil (India)",
	"Telugu (India)",
	"Thai (Thailand)",
	"Turkish (Türkiye)",
	"Ukrainian (Ukraine)",
	"Urdu (India)",
	"Vietnamese (Vietnam)",
	"Welsh (United Kingdom)",
];
